spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: rehouseweb@gmail.com
    password: xncffcglusbqwtfu
    port: 587
    properties:
      mail:
        ssl:
          enable: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    protocol: smtp
    test-connection: false